### PR TITLE
fix build with vecty breaking changes on vecty.ComponentOrHTML

### LINKED ISSUE #90: component: Package doesn’t build with latest Vecty API.
```
$ go build ./...
# github.com/shurcooL/Go-Package-Store/component
component/presentation.go:32:4: undefined: prop.Class
component/presentation.go:37:17: undefined: prop.Class
component/presentation.go:48:17: undefined: prop.Class
component/presentation.go:105:20: cannot use p (type *RepoPresentation) as type vecty.Component in argument to vecty.Rerender:
        *RepoPresentation does not implement vecty.Component (wrong type for Render method)
                have Render() *vecty.HTML
                want Render() vecty.ComponentOrHTML
component/presentation.go:134:18: undefined: prop.Class
component/presentation.go:179:17: undefined: prop.Class
component/presentation.go:194:17: undefined: prop.Class
component/presentation.go:219:17: undefined: prop.Class
component/presentation.go:280:17: undefined: prop.Class
component/updates.go:15:17: undefined: prop.Class
component/updates.go:15:17: too many errors
```

This is from an up-to-date clone, after doing `go get -d` on the dependencies. I might be doing something wrong, but I think I should be able to just build this.

Note that building the main binary still works.

### PR DESCRIPTION
**Pull request by chemidy**
From [Changelog](https://github.com/gopherjs/vecty/blob/master/doc/CHANGELOG.md#nov-4-2017-pr-158-major-breaking-change) :
- Replace Render() *vecty.HTML with  Render() vecty.ComponentOrHTML
- Replace prop.Class() with vecty.Class()

Fixes #90.

### CODE REVIEW

**Comment by shurcooL** [comment]
Thank you for the PR and linking the relevant vecty changelog; it's helpful. I'll apply this soon.

File: component/presentation.go [hunk 1]
```diff
@@ -26,15 +26,15 @@ type RepoPresentation struct {
 }
 
 // Render renders the component.
-func (p *RepoPresentation) Render() *vecty.HTML {
+func (p *RepoPresentation) Render() vecty.ComponentOrHTML {
 	return elem.Div(
 		vecty.Markup(
-			prop.Class("list-entry go-package-update"),
+			vecty.Class("list-entry go-package-update"),
```
Comment (shurcooL) [inline component/presentation.go]: This should be `vecty.Class("list-entry", "go-package-update")` to comply with the [vecty API](https://github.com/gopherjs/vecty/blob/master/doc/CHANGELOG.md#oct-14-2017-pr-155-major-breaking-change):

> Migrating users must use the new function and split their classes into separate strings, rather than a single space-separated string.

I can fix this.
